### ISSUE TITLE
Performance issue when typing between bracket

### ISSUE THREAD

**Issue by kwonoj** [Durzn/BracketHighlighter#1]
Typing characters between bracket which highlights in-typing text makes typing extremely slow:

- without bracket highlighter

![image](https://user-images.githubusercontent.com/1210596/70383762-1599ab00-1928-11ea-81c2-fbf5755cea49.png)

Task takes about 20ms

- with bracket highlighter

![image](https://user-images.githubusercontent.com/1210596/70383764-20ecd680-1928-11ea-96ea-0dc696113911.png)

Task takes about 240ms

**Comment by Durzn** [comment]
Yes, this happens because every decoration has to be redrawn with each written symbol if the cursor is at the parenthesis. I'm thinking about a solution, but it's most likely gonna end up with temporarily disabling the extension, so there will be no markup while typing.
If you don't mind me asking, how do you get these stats?

**Comment by kwonoj** [comment]
Probably worth to try debounce decoration change when input event keep occurring inside of decorated area. For perf profile I just used vs code's devtools.

**Comment by Durzn** [comment]
Could you check if it's better for you with version 1.2.1?

**Comment by Durzn** [comment]
Fixed with starting with version 1.2.1
