### ISSUE TITLE
is it possible to check if brackets are escaped ?

### ISSUE THREAD

**Issue by ctf0** [Durzn/BracketHighlighter#11]
thank you so much for this, the builtin bracket match sadly doesn't always work as expected 😢 .

anyway, the feature is mostly for brackets within regex, ex,
```js
`(?<=(${this.regex})\()`
```

if u move the cursor at `\()` it will highlight both which is incorrect as the expected would be `(?<=(${this.regex})\()`, so is that possible to do or its up for the parser to decide ?

**Comment by Durzn** [comment]
hi, im not completely sure i understand your question. if i put the cursor between \ and ( from the end of your example only the correctly matching () is highlighted. do you want everything to be highlighted when the cursor is at the first opening parenthesis? (i.e. here: "(?" ) if that is expected, then i don't see a matching closing parenthesis in your example.

edit: just to make sure we're on the same page:
this is what happens right now (undesired behavior)
![highlighExample1](https://user-images.githubusercontent.com/27031091/92519442-3e820000-f21a-11ea-87b7-b4a77b2b3762.png)
and this is what you would expect to happen?
![highlightExample2](https://user-images.githubusercontent.com/27031091/92519444-3f1a9680-f21a-11ea-9330-99af3a3f2e0f.png)

im not sure if this extension is really suitable for regex to be honest since not every symbol always has a matching symbol which can be used for highlighting (in your case the first parenthesis).

**Comment by ctf0** [comment]
the `\(` is a single opening bracket, so the correct one should be hl the first & last of `(?<=(${this.regex})\()` no extra brackets are needed like in the second img/

> im not sure if this extension is really suitable for regex to be honest since not every symbol always has a matching symbol which can be used for highlighting (in your case the first parenthesis).

its really not a big deal, since 90% of the brackets are correctly highlighted, but i though if we can make the ext slightly more smart, then why not 🥇

**Comment by Durzn** [comment]
ill look into it, however i hadn't thought of that use case when creating the extension, so it might be hard to get working now.

**Comment by Durzn** [comment]
i added support for escaped symbols in commit 7280f5e 
ill push this to the marketplace as soon as i can, it will take a few days since im not at home right now.
this is what it looks like if the regex mode is enabled:
![highlightExample](https://user-images.githubusercontent.com/27031091/92568360-59d32680-f27f-11ea-9e7e-6bedb80dbefc.png)

**Comment by ctf0** [comment]
np, if u want me to test it b4 publish, u can send me the vsix file.

**Comment by Durzn** [comment]
that would be really helpful, thanks!
please change the file ending to .7z instead of .zip to extract it.
if there is any other functionality for regex which needs to be included, please tell me since i don't have to use them very often.
[bracketHighlighterRegex.zip](https://github.com/Durzn/BracketHighlighter/files/5195797/bracketHighlighterRegex.zip)
to test the functionality, please enable the new "regex mode" in the settings.

**Comment by ctf0** [comment]
working perfectly, it actually solved another issue of the opening brace was hl the wrong closing ex.
```
(`(?<=(${this.regex})\\()['"](((?![$*]).)*?)['"]`, 'g')
```

`(?` was hl `g')` as its closing bracket.

thanx again for your hard work and quick response. 🏆
