### ISSUE TITLE
Option to change the font size of highlighted text breaks default zoom feature

### ISSUE THREAD

**Issue by ALIENQuake** [Durzn/BracketHighlighter#13]
Hi,

Option to change the font size of highlighted text breaks default zoom feature:
![image](https://user-images.githubusercontent.com/365255/98958565-b3b3cf00-2502-11eb-93e4-7925508d3e6c.png)

**Comment by Durzn** [comment]
Hi, thanks for bringing that to my attention, that case hadn't crossed my mind. Since I cannot get the current text size of the editor, I have to rely on the configured font size of the editor, which doesn't seem to scale with the zoom.
Since the scaling was rather hacky, I'll remove the feature and everything should work normally.

Edit: Should this ever become part of https://code.visualstudio.com/api/references/vscode-api#TextEditorDecorationType I'll add it back in.

**Comment by Durzn** [comment]
Reverted in version 2.2.2, sorry if this is a feature you used.

**Comment by ALIENQuake** [comment]
@Durzn I didn't use it. Fixing bug was more important than this feature, thanks!
