### ISSUE TITLE
Feature Request: Do not highlight if in comment

### ISSUE THREAD

**Issue by parmigggiana** [Durzn/BracketHighlighter#16]
As per the title, would it be possible to disable the highlighting if the brackets are in a comment? 
It's not an important feature of course, but it would be nice ^^

**Comment by Durzn** [comment]
Hi, I'll keep this request in mind, however I don't see this coming in the near future, since this would open a can of worms depending on the language one works with. C alone has 3 different styles to comment code, one of which requires knowledge about the actual code. Not sure about the ocean of other languages out there.
One could argue that not all comment styles would need to be supported, but the extension so far is language agnostic and I'd like to keep it that way.

Regardless, thank you for using the extension and requesting this feature :).

**Comment by parmigggiana** [comment]
Thanks for answering! That's unfortunate, I supposed vscode had something in the api to figure out a comment like for the syntax highlighting, but yeah that sounds like way too much pain for something trivial
