### ISSUE TITLE
FR: Outline mode

### ISSUE THREAD

**Issue by st-schneider** [Durzn/BracketHighlighter#3]
would it be possible to have the whole range of the bracket outlined like so?
https://user-images.githubusercontent.com/13774879/31192876-d39b052c-a918-11e7-92ed-f3acb6049b1f.png

**Comment by Durzn** [comment]
I tried it and it looked like this.
![wholeOutline](https://user-images.githubusercontent.com/27031091/70551379-b92cca80-1b77-11ea-895a-7e64edf24c69.png)
It looks like you want it if you set a background color instead of a border.
![wholeOutlineBgClr](https://user-images.githubusercontent.com/27031091/70552170-20974a00-1b79-11ea-9520-a2be9726a153.png)

Personally, I don't like it however if you have a use case for it, it can be added.

**Comment by Durzn** [comment]
Closing this, since the desired behavior is not achievable.
